### ISSUE TITLE
Install modules 

### ISSUE THREAD

**Issue by RedxLus** [josh-thurston/easyBEATS#11]
I'm fiddling for something with SIEM from ELK stack and suricata on a raspberry pi. 
But when I want to install a module later it doesn't work:

`cd /usr/share/filebeat/bin`
`./filebeat modules enable suricata`

The following error appears:
 **Error initializing beat: error loading config file: stat filebeat.yml: no such file or directory**

Means that I can only use the plugins that are already in the /etc/filebeat/modules.d folder?

**Comment by benvanloock** [comment]
FWIW it states the filebeat.yml was not found. Maybe try with :
./filebeat modules enable suricata -c /etc/filebeat/filebeat.yml
