### ISSUE TITLE
Compile error with cannot load io/fs

### ISSUE THREAD

**Issue by ageoffri** [josh-thurston/easyBEATS#16]
I'm using the script and getting the below error.

build github.com/elastic/beats/v7/filebeat: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1: build github.com/elastic/beats/v7/filebeat: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

**Comment by josh-thurston** [comment]
i just ran the script on my raspi and didnt have any issues.  I tried, but couldnt reproduce the error you have.  
Did you follow the instructions and edit the script to pull the latest version of filebeat down?
