### ISSUE TITLE
mage: command not found

### ISSUE THREAD

**Issue by V0lundr** [josh-thurston/easyBEATS#18]
Hi, I'm having some issues during the installation. All goes well until the point when installing metricbeat/filebeat:

_Proceeding without swap space.
---------------------------------------------------------------
Compiling Beats...
Compiling metricbeat
./easyBEATS: line 28: mage: command not found
metricbeat created
Compiling filebeat
./easyBEATS: line 28: mage: command not found
filebeat created
---------------------------------------------------------------
Installing on your local system...
Installing metricbeat locally...
cp: cannot stat '/tmp/beats/metricbeat/metricbeat': No such file or directory
cp: cannot stat '/root/easyBEATS/services/metricbeat.service': No such file or directory
Failed to enable unit: Unit file metricbeat.service does not exist.
Installing filebeat locally...
cp: cannot stat '/tmp/beats/filebeat/filebeat': No such file or directory
cp: cannot stat '/root/easyBEATS/services/filebeat.service': No such file or directory
Failed to enable unit: Unit file filebeat.service does not exist.
Cleaning up working files..._

Thanks a lot

p.s. Installation was done on Raspbian (Raspberry Pi 4)

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

**Comment by vannordenn** [comment]
i had similar problem, changing one line in localBEATS file solved it:
WORKING_DIR="beat-factory" #this directory will be created in /home/pi 

I changed "beat-factory" for "username/beat-factory".

**Comment by josh-thurston** [comment]
thanks for sharing @vannordenn 
that totally makes sense now that you point that out.  Ill have to make updates.  Thank you for the help on this.

/JT
