### ISSUE TITLE
 filebeat won't start

### ISSUE THREAD

**Issue by ahiyaz** [josh-thurston/easyBEATS#8]
hi

ive used your easybeat script on my ubuntu 18.0.14 Pi4 to install filebeat but filebeat won't start.
ive installed it as root (sudo bash)
after installing bit and cloning your code ive updated the script options as follow:

- USE_SWAP=false
- BEAT_VERSION_NUM="7.7.1"
- BEAT_VERSION="17029"

and run the script.
the script seems to run successfully but i can't start it.
i saw that /etc/filebeat directory is empty and so directories under /usr/share/filebeat

could you help me understand what went wrong?
this great tool could save me lots of hassle.

thanks in advace

**Comment by ahiyaz** [comment]
hi
this is the log i get while installing
seems that it cant find beat-factory dir
ive tried to creat it and run again but end with the same result 


root@ubuntu:~# cd easyBEATS/
root@ubuntu:~/easyBEATS# ./easyBEATS
---------------------------------------------------------------
Performing system update...
System update complete
---------------------------------------------------------------
Working directory already exists
---------------------------------------------------------------
Installing dependencies...
<pkgutil.ImpLoader instance at 0xffff92851050>
Installing go...
--2020-06-10 13:26:09--  https://dl.google.com/go/go1.13.8.linux-armv6l.tar.gz
Resolving dl.google.com (dl.google.com)... 172.217.19.142, 2a00:1450:4006:806::200e
Connecting to dl.google.com (dl.google.com)|172.217.19.142|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98281295 (94M) [application/octet-stream]
Saving to: ‘go1.13.8.linux-armv6l.tar.gz’

go1.13.8.linux-armv6l.tar.gz            100%[============================================================================>]  93.73M  17.9MB/s    in 5.7s

2020-06-10 13:26:15 (16.3 MB/s) - ‘go1.13.8.linux-armv6l.tar.gz’ saved [98281295/98281295]

Reading package lists... Done
Building dependency tree
Reading state information... Done
libpcap-dev is already the newest version (1.8.1-6ubuntu1.18.04.1).
The following packages were automatically installed and are no longer required:
  linux-raspi2-5.3-headers-5.3.0-1017 linux-raspi2-5.3-headers-5.3.0-1022
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Dependency installation complete.
---------------------------------------------------------------
Copying source code from Elastic
./easyBEATS: line 52: cd: /home/ubuntu/beat-factory/src/github.com/elastic: No such file or directory
./easyBEATS: line 53: /usr/share/go/bin/go: No such file or directory
---------------------------------------------------------------
Checking out Beats version 7.7.1
./easyBEATS: line 46: cd: /home/ubuntu/beat-factory/src/github.com/elastic/beats: No such file or directory
error: pathspec '17029' did not match any file(s) known to git.
---------------------------------------------------------------
Proceeding without swap space.
---------------------------------------------------------------
Compiling Beats...
Compiling filebeat
./easyBEATS: line 25: cd: /home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat: No such file or directory
./easyBEATS: line 26: /usr/share/go/bin/go: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
filebeat created
---------------------------------------------------------------
Installing on your local system...
Installing filebeat locally...
cp: cannot stat '/home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat/filebeat': No such file or directory
cp: cannot stat '/home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat/filebeat.reference.yml': No such file or directory
cp: cannot stat '/home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat/filebeat.yml': No such file or directory
cp: cannot stat '/home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat/module': No such file or directory
cp: cannot stat '/home/ubuntu/beat-factory/src/github.com/elastic/beats/filebeat/modules.d/': No such file or directory
Cleaning up working files...
Working directory deleted.
Complete

**Comment by l3d00m** [comment]
> error: pathspec '17029' did not match any file(s) known to git.

There's your issue, you specified the wrong commit hash at the top of your easyBeats file with`BEAT_VERSION="17029"` I'd recommend that you just use `BEAT_VERSION="v7.7.1"` instead of the commit hash.
